verbose: false
world_frame: "ascento/handheld_odom_frame"
# world_frame: "world"
color_mode: "normals"

# method: "projective"
# sensor_horizontal_resolution: 1024
# sensor_vertical_resolution: 64
# sensor_horizontal_field_of_view_degrees: 360
# sensor_vertical_field_of_view_degrees: 33.222
# integrator_threads: 8

tsdf_voxel_size: 0.10
truncation_distance: 0.80
max_weight: 1000
pointcloud_queue_size: 1
max_ray_length_m: 3.0
min_ray_length_m: 0.3
max_consecutive_ray_collisions: 1
use_const_weight: true
use_weight_dropoff: false

publish_pointclouds_on_update: true
slice_level: 1.0
publish_slices: true
update_mesh_every_n_sec: 2.0

pointcloud_deintegration_queue_length: 100

publish_tsdf_map: true
publish_map_every_n_sec: 8.0 # This parameter defines how long it takes till a new submap is created.
publish_map_with_trajectory: true
